### ISSUE TITLE
Getting

### ISSUE THREAD

**Issue by theschles** [hfern/winix#9]
```
➜ winixctl login
You need to signup for a Winix account & associate your device in the phone app before using this.
Username (email): foo+bar@mydomain.com
Password: <not shown>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jose/backends/__init__.py", line 2, in <module>
    from jose.backends.cryptography_backend import get_random_bytes  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jose/backends/cryptography_backend.py", line 4, in <module>
    from cryptography.exceptions import InvalidSignature, InvalidTag
ModuleNotFoundError: No module named 'cryptography'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/winixctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/winix/cmd.py", line 326, in main
    cls(args, config=Configuration("~/.config/winix/config.json")).execute()
  File "/usr/local/lib/python3.10/site-packages/winix/cmd.py", line 111, in execute
    return self._login()
  File "/usr/local/lib/python3.10/site-packages/winix/cmd.py", line 120, in _login
    self.config.cognito = login(username, password)
  File "/usr/local/lib/python3.10/site-packages/winix/auth.py", line 25, in login
    from warrant_lite import WarrantLite
  File "/usr/local/lib/python3.10/site-packages/warrant_lite/__init__.py", line 16, in <module>
    from jose import jwt, JWTError
  File "/usr/local/lib/python3.10/site-packages/jose/jwt.py", line 6, in <module>
    from jose import jws
  File "/usr/local/lib/python3.10/site-packages/jose/jws.py", line 5, in <module>
    from jose import jwk
  File "/usr/local/lib/python3.10/site-packages/jose/jwk.py", line 1, in <module>
    from jose.backends.base import Key
  File "/usr/local/lib/python3.10/site-packages/jose/backends/__init__.py", line 5, in <module>
    from jose.backends.pycrypto_backend import get_random_bytes  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/jose/backends/pycrypto_backend.py", line 7, in <module>
    from Crypto.PublicKey import RSA
  File "/usr/local/lib/python3.10/site-packages/Crypto/PublicKey/RSA.py", line 137
    e, d, n, p, q, u = [self._key[comp] for comp in 'e', 'd', 'n', 'p', 'q', 'u']
                                                       ^
SyntaxError: invalid syntax
```

Potential causes:
* My Winix email login uses a `+` -- a nice feature offered by Google G-Suite so I can see if my registered email address ends up on some spam list
* My Winix password is very complicated, so that might also be getting things in trouble.  Perhaps it needs to be surrounded with quotes?

**Comment by dstamen** [comment]
I have this same issue, even trying something like a normal password im getting this too

**Comment by dstamen** [comment]
I got around that error doing pip install cryptography. but now get this one

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='us.mobile.winix-iot.com', port=443): Max retries exceeded with url: /registerUser (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```

seems to be certificate related.

**Comment by dstamen** [comment]
ended up using this for now to get my device id. https://github.com/banzalik/homebridge-winix-c545/wiki/How-to-get-device-ID

**Comment by theschles** [comment]
Yeah needed to `pip install —upgrade cryptography`
